resilience4j.timelimiter:
  instances:
    ratingService:
      timeoutDuration: 2s
      cancelRunningFuture: true
    someOtherService:
      timeoutDuration: 1s
      cancelRunningFuture: false
---
rating:
  service:
    endpoint: http://localhost:7071/ratings/
    
server:
  servlet:
    session:
      timeout: 60s
  tomcat:
    threads:
      max: 200
      
    
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui

